IMDB:
    # Log into your IMDb account from a web browser, inspect the cookies and retrieve the value of cookie:
    # name: at-main | domain: .imdb.com
    # You need to replace this value with your own, the default value is for illustrative purposes only
    COOKIEATMAIN: Atza|IwEBIOHIrU3lOSDuhilHmbrn4qaeSXdoQyU6eYQIS1XuuZfq2vw9yEwz8vwerSZBmNBY2bi3p6PDobU8344JY2GYrfnCdN82XfeMF1jFpdl38sb9-hRNe1rOtRDkjilHlgXp21w9F7aHqwfzph_ght2MwtKbPr9cjULZKnbR2xg4EltyHPdMirmwDzG42zcDokyVh_YzpK9lZEB5NOr7XzgamSwhs40TznElNynPe0m_ukv8sw
    # Log into your IMDb account from a web browser, inspect the cookies and retrieve the value of cookie:
    # name: ubid-main | domain: .imdb.com
    # You need to replace this value with your own, the default value is for illustrative purposes only
    COOKIEUBIDMAIN: 131-9074478-8950830
    # Array of IMDb lists that you would like synced to Trakt
    # If this array is empty, all IMDb lists will be synced to Trakt
    # Keep in mind the maximum number of lists you can have in Trakt: https://twitter.com/trakt/status/1536751362943332352
    # In order to get the ID of an IMDb list, open it from a browser - the ID is in the URL with format ls#########
    LISTS:
        - ls521051937
        - ls529890900
SYNC:
    # Sync mode to be used when running the application
    # The value must be one of the following:
    #   full     - sync all IMDb items by adding, deleting and updating Trakt resources
    #   add-only - sync only newly added IMDb items to Trakt
    #   dry-run  - identify what IMDb items would be added, deleted or updated on Trakt
    MODE: full
    # Whether to skip history sync or not. If set to true, history sync will be skipped
    # IMDb doesn't offer functionality similar to Trakt history, hence why there can't be a direct mapping between them
    # The syncer will assume you have watched an item if you've submitted a rating for it
    # If the above is satisfied and your history for this item is empty, then a new history entry will be added...
    SKIPHISTORY: true
TRAKT:
    # Trakt app client ID
    # You need to replace this value with your own, the default value is for illustrative purposes only
    CLIENTID: f1545a6370620a89c6d3ca6856c64f36bc5463e7d0f3113628cbbae4f87bea90
    # Trakt app client secret
    # You need to replace this value with your own, the default value is for illustrative purposes only
    CLIENTSECRET: efedd4539254117ed96856b6f0f556c5abd5909660dc2475c33044cb12c7de87
    # Trakt account email address (not to be confused with username)
    # You need to replace this value with your own, the default value is for illustrative purposes only
    EMAIL: luca-corti@hotmail.it
    # Trakt account password
    # You need to replace this value with your own, the default value is for illustrative purposes only
    PASSWORD: Juventus1#1
